apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: swift-hawk-python 
  janus-idp.io/tekton: swift-hawk-python
  backstage.io/kubernetes-id: swift-hawk-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: swift-hawk-python
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  