apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: swift-hawk-python-gitops
  description: This is GitOps manifest for swift-hawk-python   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-name: swift-hawk-python
    janus-idp.io/tekton: swift-hawk-python 
    backstage.io/kubernetes-id: swift-hawk-python 
    backstage.io/techdocs-ref: dir:. 
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:swift-hawk-python
