apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: swift-hawk-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: swift-hawk-python 
  name: swift-hawk-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: swift-hawk-python 
